title: Ran Luo
description: > # this means to ignore newlines until "baseurl:"
  This website is for showing my works.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ran Luo # add your name
author-img: myphoto.png # add your photo
about-author: I am currently pursuing the Ph.D. degree in Computer Engineering at the University of New Mexico(UNM), Albuquerque, New Mexico. I will graduate at spring 2020. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: lrquad # add your Github handle
social-linkedin: luoranrl # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-146694270-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
